---
- name: Reset windows time clock
  hosts: windows
  tasks:
    - name: Stop time service
      ansible.windows.win_shell: net stop w32time

    - name: unregister time service
      ansible.windows.win_shell: w32tm /unregister

    - name: reregister time service
      ansible.windows.win_shell: w32tm /register

    - name: restart time service
      ansible.windows.win_shell: net start w32time

    - name: resync time service
      ansible.windows.win_shell: w32tm /resync
